### ISSUE TITLE
Missing contact information on the repo.

### ISSUE THREAD

**Issue by kilogold** [darkfriend77/SubstrateNetApi#13]
> SubstrateNetApi is written in NETStandard2.0 to provide maximum compatibility for Unity3D. Feedback, constructive critisme and disscussions are welcome and will help us to improve the API!

Where do we have discussions or criticism? 
I am interested in using this repo more seriously but not sure where to discuss technical details.

**Comment by kilogold** [comment]
Got creative with Google:
https://dotmog.com/

**Comment by darkfriend77** [comment]
You can discuss it here or contact us directly admin@dotmog.com
