### ISSUE TITLE
New protocol version  14

### ISSUE THREAD

**Issue by tryexceptend** [darkfriend77/SubstrateNetApi#22]
Hi. It is not possible to send a deposit according to protocol 14.
Losg:

2021-10-12 23:45:51.0247 Connected to Websocket. 
2021-10-12 23:45:51.0247 Listening to websocket. 
2021-10-12 23:45:51.0247 Invoking request[state_getMetadata, params: ]

**Comment by darkfriend77** [comment]
By version 14 you mean the new metadata?

If so then you will have to use the refactored, Ajuna.NetApi which is for substrate version from monthly-2021-10 and newer.

I can release a version that is integrating the full node and/or node-template for monthly-2021-10 if you're looking for something like that.

**Comment by tryexceptend** [comment]
I just need to implement the sending of funds. If you use Ajuna.NetApi, then return an error

`
Ed25519.KeyPairFromSeed(out var publicKey, out var privateKey, miniseed);
Account accountZurich = Account.Build(KeyType.Ed25519, privateKey, publicKey);
string address = "5...";
var balance = new Balance();
var am = BigInteger.Parse("2000000000000");
balance.Create(am);
var accountId = new AccountId();
accountId.Create(Utils.GetPublicKeyFrom(address));
var byteList = new List<byte>();
byteList.AddRange(accountId.Encode());
byteList.AddRange(balance.Encode());
var balanceTransfer = new Method(5, "Balances",0, "transfer" ,byteList.ToArray());
SubstrateClient client = new(new Uri("wss://westend-rpc.polkadot.io"));
await client.ConnectAsync();
var reqResult = await client.Author.SubmitExtrinsicAsync(balanceTransfer, accountZurich, 0, 64, cancellation.Token);
client.Dispose();
`

`
StreamJsonRpc.RemoteInvocationException: 'Verification Error: Runtime error: Execution failed: Other("Wasm execution trapped: wasm trap: unreachable\nwasm backtrace:\n    0: 0x2bc7 - <unknown>!rust_begin_unwind\n    1: 0x2984 - <unknown>!core::panicking::panic_fmt::h3ab5417155b7ba3b\n    2: 0x392af8 - <unknown>!TaggedTransactionQueue_validate_transaction\n")'
`

**Comment by tryexceptend** [comment]
Sorry. Specified the wrong module index.

**Comment by darkfriend77** [comment]
Okay, will close this issue then, just ask if you need some help.
