### ISSUE TITLE
Error while making async connection.

### ISSUE THREAD

**Issue by TJ-alchemist** [darkfriend77/SubstrateNetApi#23]
I am getting the below error when making a connection to the client,
```
IndexOutOfRangeException: Index was outside the bounds of the array.
SubstrateNetApi.MetaDataParser.ExtractString (System.Byte[] m, System.Int32& p) (at <e6961ae183514faf941a4c1e7e63479b>:0)
```
This is my code
```cs
public async void MakeConnection() 
{
    string WEBSOCKETURL = "ws://127.0.0.1:9944";
    SubstrateClient client = new SubstrateClient(new Uri(WEBSOCKETURL));
    await client.ConnectAsync(); // Error at this line.
    await client.CloseAsync();
    Debug.Log("Connection has been established and closed!");
} 
```

And is there a way to get one's personal substrate wallet address instead of Alice's or Bob's?

**Comment by darkfriend77** [comment]
What substrate version are you using? Seems like not 3.0 Apollo telease, right?

For the new versions you will need the Ajuna.NetApi, we will have the SDK ready to build your node extension in a few days.

**Comment by TJ-alchemist** [comment]
> What substrate version are you using? Seems like not 3.0 Apollo telease, right?
> 
> For the new versions you will need the Ajuna.NetApi, we will have the SDK ready to build your node extension in a few days.

No i am using the latest version of substrate.
But thanks, it works with the [3.0](https://github.com/substrate-developer-hub/substrate-node-template/releases/tag/v3.0.0) substrate version.
