### ISSUE TITLE
How to make a GenericExtrinsic call?

### ISSUE THREAD

**Issue by MikeHuntington** [darkfriend77/SubstrateNetApi#4]
I'm using the following code to send a call to a method on my pallet. However I don't know what the Author property is of '_client'. Also I don't get a return result value from this and also no errors.

also how do I sign a call to an extrinsic?

`byte[] pubKey = Utils.HexToByteArray("5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY");
            Account alice = new Account(KeyType.ED25519, pubKey);

            GenericExtrinsicCall startGameCall = new GenericExtrinsicCall("mypallet", "my_method");
            var reqResult = await _client.Author.SubmitExtrinsicAsync(startGameCall, alice, 0, 64, CancellationToken.None);`

**Comment by darkfriend77** [comment]
Okay, 

you have a valid connection? [example](https://github.com/dotmog/SubstrateNetApi/blob/91f1ebeea5a32b2757b3cad6ce0490514f2866e3/DemoApiTest/Program.cs#L62)

the account that is submitting the extrinsic needs to have a private key.
https://github.com/dotmog/SubstrateNetApi/blob/91f1ebeea5a32b2757b3cad6ce0490514f2866e3/DemoApiTest/Program.cs#L64

the payload is signed as part of the extrinsic submission.

If the connection is working you might check in the metadata file if your extrinsic is correct, to do this just call.
`Console.WriteLine(client.MetaData.Serialize());`
after the connection, write it to a file and check for your pallet. 
should look something like this ... 
```
            {
               "Name":"my_method",
               "Arguments":[
                  
               ],
               "Documentations":[
                  "Description ... "
               ]
            },
```

Do you have NLog activated, probably you would see what is missing in the log.

**Comment by MikeHuntington** [comment]
Thanks for the reply! Just to be clear I'm using Unity with the library. I'm able to make a valid connection and pull all the metadata.

There doesn't seem to be a "Build" function on the Account object. There isn't even a namespace called "SubstrateNetApi.Model.Types". I'm using the dlls that were in the example unity project. Are those out of date?

here is the repo that I'm using for the dlls https://github.com/darkfriend77/Unity3DExample

**Comment by MikeHuntington** [comment]
Ahhh so that was the problem. The UnityExample is using older libs. Once I updated to the new dll and used the example code you provided, it all worked! Thank you.

So my last question related to that is that you mentioned the payload is signed as part of the submission. Is there a way intercept the message before it is signed and allow the user to approve it, the same way that the polkadot JS wallet does?

For example if I'm building at WebGL app with unity, I want to send the message to the browser so that the user can sign for the message in PolkadotJS wallet extension. That way I don't have access to the user's private keys. If you would be so kind to maybe point me in the right direct to getting that message before signing it in my application that would be great. and also a way to not NEED the user's private keys.

**Comment by darkfriend77** [comment]
okay, I can point you where the main logic around extrinsic is situated.

https://github.com/dotmog/SubstrateNetApi/blob/5cc592660bf65be87f66f08e4a9bf91a0a6f8330/SubstrateNetApi/SubstrateClient.cs#L410

Currently the option is set for signed to be true, if this use case you referee is a valid one I can decouple signing and creating the extrinsic from each other.

The thing that would do this is interfering on the UncheckedExtrinsic return from RequestGenerator.SubmitExtrinsic(signed:false ...
https://github.com/dotmog/SubstrateNetApi/blob/5cc592660bf65be87f66f08e4a9bf91a0a6f8330/SubstrateNetApi/SubstrateClient.cs#L432

then take the payload sign it by your external webgl then put it back into the extrinsic as signature.

**Comment by darkfriend77** [comment]
Here is a branch where I decoupled the UnCheckedExtrinsic and added the signed flag.

https://github.com/dotmog/SubstrateNetApi/tree/singed_external

You can use signed = false, then take the payload sign it externaly then adding the signature to the uncheckextrinsic .. and send it to the node .. 
https://github.com/dotmog/SubstrateNetApi/blob/ebbd812aa41bfffeb1829a7aea2e0f7c7dd08116/SubstrateNetApi/Modules/Author.cs#L37

**Comment by MikeHuntington** [comment]
@darkfriend77 creating the message and sending it to webgl to be signed worked perfectly. I got a valid signature back from PolkadotJS extention and I returned that signature back to Unity... but I may have misuderstood the code. What method would I call now with my newly created signature back inside Unity?

Just looking at the code it seems like the method I would want to call is marked as internal (internal async Task<UnCheckedExtrinsic> GetExtrinsicParametersAsync)

**Comment by darkfriend77** [comment]
The process would be like so ... 
Create an `UncheckedExtrinsic` by using

`await _client.GetExtrinsicParametersAsync(callArguments, account, tip, lifeTime, signed: true, token);`

made it public now

Get the Payload from it `uncheckExtrinsic.GetPaload`
.. send the payload to your webgl extension to be signed
Call `uncheckExtrinsic.AddPayloadSignature` where you give the signed payload.
then send of the uncheckextrisnic with ...

`await SubmitExtrinsicAsync(Utils.Bytes2HexString(extrinsic.Encode()), token);`

**Comment by MikeHuntington** [comment]
That was a big help! Thank you very much!!
