### ISSUE TITLE
is it possible to get a preset nuget package config

### ISSUE THREAD

**Issue by 2075** [darkfriend77/SubstrateNetApi#7]
...containing all required dependencies?

i am on macos, therefore nuget seems a bit shaky, don't know if it is the unity3d implementation or nuget itself, but it seems hard to resolve all required packages, as not all packages can be installed. or is the plugin windows ide specific?

**Comment by 2075** [comment]
<img width="905" alt="grafik" src="https://user-images.githubusercontent.com/1140449/113064205-d810ff00-91b6-11eb-9372-204a09a9e370.png">

**Comment by 2075** [comment]
list just gets longer the more dependencies i try to resolve
<img width="1031" alt="grafik" src="https://user-images.githubusercontent.com/1140449/113064709-d8f66080-91b7-11eb-9d64-08ad9fa9c460.png">

**Comment by darkfriend77** [comment]
We used NuGet for Unity, but it seems there is a bug, so we currently import a fixed set of DLL's

https://github.com/darkfriend77/Unity3DExample/tree/master/Assets/Plugins

Here is the link to an example unity template project, for now.

https://github.com/GlitchEnzo/NuGetForUnity

, but we need to check if the bug in NuGetForUnity is fixed now this would automate the full nuget step.

**Comment by 2075** [comment]
yes, i saw it in your docs already. sadly the current nuget version does not fix anything in that regard. is the unit3d example using the current versions? will check it again.

**Comment by darkfriend77** [comment]
yes I updated it a few hours ago.

**Comment by 2075** [comment]
so this is related to the old version?

```
Assets/Main.cs(22,23): error CS0234: The type or namespace name 'Model' does not exist in the namespace 'SubstrateNetApi' (are you missing an assembly reference?)
```

```
using NLog;
using NLog.Config;
using NLog.Targets;

using SubstrateNetApi;
using SubstrateNetApi.Model.Calls;
using SubstrateNetApi.Model.Rpc;
using SubstrateNetApi.Model.Types;
using SubstrateNetApi.Model.Types.Enum;
using SubstrateNetApi.Model.Types.Struct;
using SubstrateNetApi.TypeConverters;
```

**Comment by darkfriend77** [comment]
yes, it's related to using an old version.
