### ISSUE TITLE
which dotnet core is required?

### ISSUE THREAD

**Issue by 2075** [darkfriend77/SubstrateNetApi#8]
i am on macos

do i need dotnet core 5.0 or 3.1?
<img width="758" alt="grafik" src="https://user-images.githubusercontent.com/1140449/113063882-4c976e00-91b6-11eb-8c80-ba4b5d2e2677.png">

**Comment by 2075** [comment]
currently i have this installed:
<img width="633" alt="grafik" src="https://user-images.githubusercontent.com/1140449/113064030-8c5e5580-91b6-11eb-90fa-ca37b8545041.png">

**Comment by darkfriend77** [comment]
We have build the API in NETStandard 2.0 this should be part of both, but for the unit tests we used NET Core 3.1

https://github.com/dotmog/SubstrateNetApi/blob/61ae33321d0b3ac369bd704c3b4db97645308e6d/SubstrateNetApi/SubstrateNetApi.csproj#L4

https://github.com/dotmog/SubstrateNetApi/blob/61ae33321d0b3ac369bd704c3b4db97645308e6d/SubstrateNetApiTest/SubstrateNetApiTests.csproj#L4

So I would suggest .NET Core 3.1

As a reference for me https://docs.microsoft.com/en-us/dotnet/standard/net-standard
