### ISSUE TITLE
How do I kill an account?

### ISSUE THREAD

**Issue by tryexceptend** [darkfriend77/SubstrateNetApi#9]
Hi! How do I transfer all funds from one account to another?

**Comment by darkfriend77** [comment]
Okay, I would use the extrinsic call transfer for that, now if you mean something like transfer max there isn't such a method which would calculate the max amount including the fees. At least I haven't found.

Maybe this can help https://www.shawntabrizi.com/substrate/substrate-weight-and-fees/

**Comment by darkfriend77** [comment]
Here Dans answer to the max amount:

> <@darkfriend77:matrix.org> Short question is there something like transfer max amount from one account to another, and having the amount including the fees to max.

yes, but afaik there is no easy UI to do this officially

https://polkadot.js.org/docs/api/start/api.tx.subs#payment-information

you can do a (hypothetical) create -> check fees -> create actual tx = total ballance - fees -> (optional) check fees match with real tx -> send tx

**Comment by tryexceptend** [comment]
Thanks! This method works

**Comment by darkfriend77** [comment]
👍
